# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "techtown/centos-7.2"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "10.2.3.10"
    ansible.vm.provision "shell", path: "install_ansible.sh"
  end
  
  config.vm.define "testbox" do |testbox|
    testbox.vm.hostname = "testbox"
    testbox.vm.network "private_network", ip: "10.2.3.20"
  end

end
