# -*- mode: ruby -*-
# vi: set ft=ruby :


nodes = {
  :ansible => {
    :hostname => "ansible",
    :ipaddress => "10.2.3.10",
    :script => "install_ansible.sh",
    :primary => true,
    :autostart => true
  },
  :node1 => {
    :hostname => "node1",
    :ipaddress => "10.2.3.20",
    :primary => false,
    :autostart => true
  },
  :node2 => {
    :hostname => "node2",
    :ipaddress => "10.2.3.30",
    :primary => false,
    :autostart => true
  },
  :node3 => {
    :hostname => "node3",
    :ipaddress => "10.2.3.40",
    :primary => false,
    :autostart => true
  }
}

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |global_config|
  global_config.vm.box = "techtown/centos-7.2"
  global_config.ssh.insert_key = false

  nodes.each do |node, options|
    global_config.vm.define node, primary: options[:primary], autostart: options[:autostart] do |node_config|
      node_config.vm.hostname = options[:hostname]
      node_config.vm.network "private_network", ip: options[:ipaddress]
      if options.has_key?(:script)
        node_config.vm.provision "shell", path: options[:script]
      end      
    end
  end
end
