---
- name: Install NTP and dependencies
  yum: name={{ item }} state=installed
  with_items:
    - libselinux-python
    - ntp
    
- name: Install the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: 
   - restart ntp
   
- name: restart ntp
  service: name="ntpd" state=restarted enabled=yes
