---
- name: Add the docker repo for yum
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: Install the docker-engine package
  yum: name=docker-engine state=present
  
- name: install python-pip for docker-py
  yum: name=python-pip state=present
  
- name: install docker-py via pip
  pip: name=docker-py
  
- name: install docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/1.7.1/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755
  
- name: Start the docker service
  service: name=docker state=started
