# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = '2'

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "techtown/centos-7.2"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  # config.vm.network "private_network", ip: "10.2.3.10"
  config.vm.hostname = "rocket-chat"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
  end
end
