# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = {
  :ansible => {
    :hostname => "ansible",
    :ipaddress => "10.99.99.10",
    :primary => true,
    :autostart => true
  },
  :node1 => {
    :hostname => "node1",
    :ipaddress => "10.99.99.20",
    :primary => false,
    :autostart => true
  },
  :node2 => {
    :hostname => "node2",
    :ipaddress => "10.99.99.30",
    :primary => false,
    :autostart => true
  }
}

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |global_config|
  global_config.vm.box = 'techtown/ubuntu-14.04'
  
  global_config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  nodes.each do |node, options|
    global_config.vm.define node, primary: options[:primary], autostart: options[:autostart] do |node_config|
      node_config.vm.hostname = options[:hostname]
      node_config.vm.network "private_network", ip: options[:ipaddress]
      if options.has_key?(:forwardport)
        node_config.vm.network "forwarded_port", guest: options[:forwardport][:guest], host: options[:forwardport][:host]
      end

    end
  end
end
