---
- hosts: all
  become: yes

  pre_tasks:
    - name: Ensure the EPEL repository is present
      yum: name=epel-release state=present

    - name: Ensure the EPEL repository GPG key is imported
      rpm_key: key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 state=present

  roles:
    - docker

