# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = '2'

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "techtown/debian-8.4.0"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.hostname = "hello-world"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
  end
end
