# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "techtown/ansible-2.0.2.0"
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "10.2.3.10"
  end
  
  config.vm.define "testbox" do |testbox|
    testbox.vm.box = "techtown/ubuntu-14.04"
    testbox.vm.hostname = "testbox"
    testbox.vm.network "private_network", ip: "10.2.3.20"
  end

end
