---
- name: Ensure the EPEL repository is present
  yum: name=epel-release state=present

- name: Ensure the EPEL repository GPG key is imported
  rpm_key: key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 state=present

- name: Install required software to run our NodeJS app.
  yum: "name={{ item }} state=present"
  with_items:
    - nodejs
    - npm

- name: Install Forever (to run our Node.js app).
  npm: name=forever global=yes state=present

- name: Ensure Node.js app folder exists.
  file: path=/opt/webapps state=directory

- name: Copy example Node.js app to server.
  copy: src=app dest=/opt/webapps

- name: Install app dependencies defined in package.json.
  npm: path=/opt/webapps/app

- name: Check list of running Node.js apps.
  command: forever list
  register: forever_list
  changed_when: false

- name: Start example Node.js app.
  command: forever start /opt/webapps/app/app.js
  when: forever_list.stdout.find('/opt/webapps/app/app.js') == -1
