# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "techtown/ubuntu-14.04"
  # config.vm.box_check_update = false
  config.vm.hostname = "ansible"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
